README.md, autoload/minpac/LICENSE-async-vim.txt, autoload/minpac/impl.vim, autoload/minpac/job.vim, doc/minpac.txt, tools/pull-async-vim.sh
This takes over #4 and closes #3.
* Update document. (Mentions async.vim and NeoVim.)
* Use git-subtree to track async.vim.
- Add a script for pulling latest async.vim.
=> Async wrapper

README.md, autoload/minpac/impl.vim, doc/minpac.txt
(This should be merged after #15.)
Support another type of hook which is invoked after all updates are finished.
This must be useful when running automated tasks or tests.
E.g.
```vim
" Quit Vim immediately after all updates are finished.
call minpac#update('', {'do': 'quit'})
```
BTW, I'm not sure what is the best name for this hook.
=> Finish-update hook

README.md, autoload/minpac/impl.vim, doc/minpac.txt, plugin/minpac.vim, test/test_minpac.vim
Support verbosity level and make log more silent by default.
Show an error message when at least one plugin fail to update.
Fix #23.
=> Support verbosity level

autoload/minpac/impl.vim
Tags files were generated only if a plugin was updated or newly installed.
So, tags for plugins which were installed manually (like minpac
itself) might not generated until next update.
Make sure that tags files are available after `minpac#update()` is called.
=> Generate helptags even if a plugin is not updated (Close #25)

autoload/minpac/impl.vim
This is required when executing :UpdateRemotePlugins.
See #37.
=> Add nvim's remote plugins to 'rtp'

README.md, autoload/minpac/impl.vim, autoload/minpac/status.vim, doc/minpac.txt, plugin/minpac.vim
Initial version of status list.
Shows only installed/updated plugins after `minpac#update()` is called.
Otherwise, returns status of all plugins.
It works similar to vim-plug, but lot of feature are missing (commit preview, handling each commit separately, etc.)
This satisfies my requirement for now, and it can be extended later on.
=> Add minpac#status() function for showing status of plugins. #56

autoload/minpac/impl.vim
The `:tcd` command was added by 8.1.1218. Minpac needs to support it.
=> Support `:tcd`

README.md, autoload/minpac/impl.vim, autoload/minpac/progress.vim, doc/minpac.txt, plugin/minpac.vim, test/test_minpac.vim
Outputting the log messages by echo commands is sometimes not good especially when updating many plugins. It may mess the display.
Add a new option to output the log message to a separate window, and enable it by default.
This adds or changes the following options in `minpac#init()`:
* progress_open: Open the progress window if set to 'horizontal', 'vertical' or 'tab'.
* status_open: Changed the default from 'vertical' to 'horizontal'.
* status_auto: Open the status window automatically if set to v:true.
Note that these options change the default behavior from minpac v2.0.x or earlier.
=> Implement progress window

README.md, autoload/minpac/impl.vim, doc/minpac.txt, plugin/minpac.vim, test/test_minpac.vim
Close #33.
When a plugin is registered with 'subdir' option, minpac will install it in:
pack/minpac/start/pluginname
as usual, then create a symlink (or a junction on Windows):
ln -s pack/minpac/start/pluginname/subdir \
pack/minpac-sub/start/pluginname
=> Implement 'subdir' option

autoload/minpac/git.vim, autoload/minpac/impl.vim
Executing external programs is slow especially on Windows.
Read the information directly from .git directory.
=> Make git operation faster

README.md, autoload/minpac/impl.vim, doc/minpac.txt, plugin/minpac.vim, test/test_minpac.vim
Close #81.
If 'pullmethod' is set to 'autostash', `--rebase --autostash` options
are used for `git pull`.
=> Add 'pullmethod' option to minpac#add()

autoload/minpac/progress.vim, autoload/minpac/status.vim
Current minpac code does not supply the first argument when calling Vim’s `bufnr()` function. This argument [only became optional recently](https://github.com/vim/vim/commit/a8eee21e75324d199acb1663cb5009e03014a13a).
The problem manifests in the message `E119: Not enough arguments for function: bufnr` when calling for example `minpac#update()` (at `minpac#update[2]..minpac#impl#update[2]..minpac#progress#open`) or `minpac#status()` (at `minpac#status[4]..minpac#status#get`).
According to `:h patches-8` (in Vim), the argument to `bufnr()` can be optional since Vim 8.1.1924 (which is [included in NeoVim since 0.4.0](https://github.com/neovim/neovim/commit/66c06dad62638106fadad389f585dc11f482c6b1)), but on versions older than that, you have to supply an empty string as the first parameter …
=> Supply first argument to bufnr()

autoload/minpac/impl.vim
See: #108
If a user has many plugins, minpac#update() may take a long time.
Use timer in it to call a subfunction.
=> Use timer to call s:update_single_plugin()

autoload/minpac.vim, doc/minpac.txt, plugin/minpac.vim
From #114, the tips on docs does not work because exists() always return 0 for autoload function until initial call.
This commit add plugin/minpac.vim which just define 'g:loaded_minpac' and rewrite document to use that.
=> Use exists('g:loaded_minpac') instead in docs

autoload/minpac/progress.vim
This is a bug fix.
Currently `wincmd w` is used to switch to progress window. This fails if the user has already switched to another tab, resulting in log messages being added to a wrong window. Must use `win_gotoid()` instead.
=> Use win_gotoid() to go to progress window

autoload/minpac/impl.vim
Occasionally, messages are printed by minpac using `s:echox_verbose()`
that contain single quotes.  When this happens, it causes the following vim error:
`
Error detected while processing function <SNR>11_start_update[2]..
<SNR>11_update_single_plugin[62]..<SNR>11_start_job[6]..<SNR>94_on_stderr[4]..
<SNR>11_job_err_cb[9]..<SNR>11_echom_verbose[1]..<SNR>11_echox_verbose:
line    8:
E121: Undefined variable: master
` 
This happens because "master" is wrapped in single quotes.
Removing the single quotes fixes this issue.
=> Remove single quotes from debug messages

autoload/minpac/progress.vim, autoload/minpac/status.vim
Fix #123.
The buffer name `[minpac progress]` can be handled as a wildcard.
Use "`=" to avoid it.
=> Avoid wildcard expansion

autoload/minpac/impl.vim, autoload/minpac/progress.vim
Fix #108.
Don't use `sleep` to wait jobs.
Also use `redraw` to update the progress window timely.
=> Fix that Vim is blocked when more than 8 plugins are registered

README.md, doc/minpac.txt
Issue #148
Using 'quit' shows the following warning:
> warning: minpac progress window not found.
Use 'qall' instead.
=> doc: Change 'quit' to 'qall'

autoload/minpac/progress.vim, autoload/minpac/status.vim
Hi, 
This PR adds `<nowait>` for each keymap to avoid waiting after press `q` or `s` if some keymaps starting with `q` or `s` are set globally. 
For me, I set a keymap `nnoremap qq <Cmd>q<CR>`, `nnoremap qt <Cmd>tabclose<CR>`, and etc. So in the progress window or status window, when I press `q` to quit the window, I have to wait a while to quit. Using `<nowait>` to eliminate this waiting. 
Thank you very much.
=> fix(keymap): add <nowait> to avoid waiting

.github/workflows/ci.yaml, README.md, autoload/minpac.vim, autoload/minpac/git.vim, autoload/minpac/impl.vim, autoload/minpac/progress.vim, autoload/minpac/status.vim, doc/minpac.txt, plugin/minpac.vim
* Avoid recursive call in timer callback (https://github.com/vim/vim/issues/13732)
* Use better function/variable names
* Implement `minpac#abort()`
* Disable <C-j> and <C-k> mappings when `g:no_minpac_maps` is defined. (Close #140)
=> Merge 'devel' into 'master'

autoload/minpac/impl.vim
The following error was shown e.g. on Vim 8.1.1847:
```
E120: Using <SID> not in a script context: s:timer_worker
```
=> Fix E120 error on older versions of Vim
